[files]
extend-exclude = [
	"*.css.map",
	"*.js.map",
	"src/wp-admin/includes/class-ftp.php",
	"src/wp-admin/includes/class-ftp-pure.php",
	"src/wp-admin/includes/class-ftp-sockets.php",
	"src/wp-admin/includes/ms.php",
	"src/wp-includes/assets/script-loader-packages.min.php",
	"src/wp-includes/formatting.php",
	"src/wp-includes/SimplePie/*",
	"src/wp-includes/ID3/*",
	"src/wp-includes/IXR/*",
	"src/wp-includes/PHPMailer/*",
	"src/wp-includes/sodium_compat",
	"src/wp-includes/Text/Diff",
	"src/js/_enqueues/vendor/*",
	"tests/phpunit/data/feed/wordpress-org-news.xml",
	"tests/phpunit/data/formatting/whole-posts.php",
	"tests/phpunit/tests/formatting/convertSmilies.php",
	"tests/phpunit/tests/formatting/wpTrimWords.php",
	"tests/phpunit/tests/functions/wpToKebabCase.php",
	"tests/phpunit/tests/l10n/*",
	"tests/phpunit/tests/multisite/isEmailAddressUnsafe.php",
	"tests/phpunit/tests/multisite/wpmuValidateBlogSignup.php",
	"tests/phpunit/tests/pomo/*",
	"tests/qunit/wp-admin/js/password-strength-meter.js"
]

[type.po]
extend-glob = ["*.po", "*.l10n.php"]
check-file = false

[default.extend-words]
# Don't correct the surname "Skelton".
Skelton = "Skelton"
# Post stati functions need to be preserved for back compat.
stati = "stati"
# Just a variable name.
struc = "struc"
# Mock_Invokable class.
Invokable = "Invokable"
# disposition-parm / disp-ext-parm
parm = "parm"
# Atom feeds
thr = "thr"
# HTML entity
curren = "curren"
# setted_site_transient.
setted = "setted"
# odf file extension.
odf = "odf"
