name: Build CI

on:
  push:
    branches-ignore: [ ]  # Run on all branches
  pull_request:
    branches-ignore: [ ]  # Run on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: syy25/scc-assignment
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: |
        # Replace these commands with the actual commands needed to install your project's dependencies.
        npm install  # Install project dependencies

    - name: Run PHPUnit Tests
      run: |
        # Set up the database for PHPUnit testing (adjust credentials as needed).
        mysql -u root -e 'CREATE DATABASE my_test_database;'
        mysql -u root -e "GRANT ALL PRIVILEGES ON my_test_database.* TO 'my_test_user'@'localhost' IDENTIFIED BY 'my_test_password';"
        
        # Run PHPUnit tests.
        phpunit
        
    - name: Clean Up PHPUnit Database
      run: |
        # Clean up the database after PHPUnit tests (optional).
        mysql -u root -e 'DROP DATABASE my_test_database;'
