name: PHP Compatibility Testing

on: [push]

jobs:

  # Runs PHP compatibility testing.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Configures caching for Composer.
  # - Sets up PHP.
  # - Logs debug information about the runner container.
  # - Installs Composer dependencies (from cache if possible).
  # - Logs PHP_CodeSniffer debug information.
  # - Runs the PHP compatibility tests.
  php-comatibility:
    name: Test PHP compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set up Composer caching
        uses: actions/cache@v2
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "latest"
          coverage: none

      - name: Log debug information
        run: |
          php --version
          composer --version

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-suggest --no-progress --no-ansi --no-interaction
          echo "vendor/bin" >> $GITHUB_PATH

      - name: Log PHPCS debug information
        run: |
          phpcs -v
          phpcs -i

      - name: Run PHP compatibility tests
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          php_codesniffer: true
          php_codesniffer_args: "--standard=phpcompat.xml.dist"
