name: PHP Compatibility Testing

on: [push]

jobs:

  # Runs PHP compatibility testing.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information about the runner container.
  # - Configures caching for Composer.
  # - Installs Composer dependencies (from cache if possible).
  # - Runs the PHP compatibility tests.
  php-comatibility:
    name: Test PHP compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer install
        run: composer install
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: './vendor/bin/phpcs'
