name: Prepare Bundled Themes for Release

on:
  pull_request:
    branches:
      - trunk
      - '3.[89]'
      - '[4-9].[0-9]'
    paths:
      # Changes to this workflow file should always verify success.
      - '.github/workflows/prepare-bundled-themes.yml'
  workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # Prepares bundled themes for release.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Installs Node.js (only when theme has a build process)
  # - Installs npm dependncies (only when theme has a build process)
  # - Runs the theme build script (only when theme has a build process)
  # - Ensures version-controlled files are not modified or deleted.
  # - Creates a ZIP file of the theme for wordpress.org.
  # - Uploads the ZIP file as an artifact.
  bundle-theme:
    name: Prepare ${{ matrix.theme }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        theme: [
            'twentytwentythree',
            'twentytwentytwo',
            'twentytwentyone',
            'twentytwenty',
            'twentynineteen',
            'twentyseventeen',
            'twentysixteen',
            'twentyfifteen',
            'twentyfourteen',
            'twentythirteen',
            'twentytwelve',
            'twentyeleven',
            'twentyten'
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        if: ${{ contains( fromJson( '["twentynineteen", "twentytwenty", "twentytwentyone"]' ), ${{ matrix.theme }} )
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install npm dependencies
        if: ${{ contains( fromJson( '["twentynineteen", "twentytwenty", "twentytwentyone"]' ), ${{ matrix.theme }} )
        run: npm ci
        working-directory: src/wp-content/themes/${{ matrix.theme }}

      - name: Build theme
        if: ${{ contains( fromJson( '["twentynineteen", "twentytwenty", "twentytwentyone"]' ), ${{ matrix.theme }} )
        run: npm run build
        working-directory: src/wp-content/themes/${{ matrix.theme }}

      - name: Ensure version-controlled files are not modified or deleted
        if: ${{ contains( fromJson( '["twentynineteen", "twentytwenty", "twentytwentyone"]' ), ${{ matrix.theme }} )
        run: git diff --exit-code
        working-directory: src/wp-content/themes/${{ matrix.theme }}

      - name: Create theme ZIP
        run: zip -r ${{ matrix.theme }}.zip src/wp-content/themes/${{ matrix.theme }}

      - name: Upload theme ZIP
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: ${{ matrix.theme }}
          path: ${{ matrix.theme }}.zip

  slack-notifications:
    name: Slack Notifications
    uses: WordPress/wordpress-develop/.github/workflows/slack-notifications.yml@trunk
    needs: [ bundle-theme ]
    if: ${{ github.repository == 'WordPress/wordpress-develop' && github.event_name != 'pull_request' && always() }}
    with:
      calling_status: ${{ needs.bundle-theme.result == 'success' && 'success' || needs.bundle-theme.result == 'cancelled' && 'cancelled' || 'failure' }}
    secrets:
      SLACK_GHA_SUCCESS_WEBHOOK: ${{ secrets.SLACK_GHA_SUCCESS_WEBHOOK }}
      SLACK_GHA_CANCELLED_WEBHOOK: ${{ secrets.SLACK_GHA_CANCELLED_WEBHOOK }}
      SLACK_GHA_FIXED_WEBHOOK: ${{ secrets.SLACK_GHA_FIXED_WEBHOOK }}
      SLACK_GHA_FAILURE_WEBHOOK: ${{ secrets.SLACK_GHA_FAILURE_WEBHOOK }}

  failed-workflow:
    name: Failed workflow tasks
    runs-on: ubuntu-latest
    needs: [ bundle-theme, slack-notifications ]
    if: |
      always() &&
      github.repository == 'WordPress/wordpress-develop' &&
      github.event_name != 'pull_request' &&
      github.run_attempt < 2 &&
      (
        needs.bundle-theme.result == 'cancelled' || needs.bundle-theme.result == 'failure'
      )

    steps:
      - name: Dispatch workflow run
        uses: actions/github-script@100527700e8b29ca817ac0e0dfbfc5e8ff38edda # v6.3.2
        with:
          retries: 2
          retry-exempt-status-codes: 418
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'failed-workflow.yml',
              ref: 'trunk',
              inputs: {
                run_id: '${{ github.run_id }}'
              }
            });
