name: Comment on PR

on:
  pull_request:
    branches:
      - trunk

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const previewLink = `https://playground.wordpress.net/wordpress.html?pr=${context.issue.number}`;
            const issueComment = `${identifier}\nPreview link: [${previewLink}](${previewLink})`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            })
    