name: Post a PR preview link

on:
  pull_request_target:
    types: [ opened, edited ]
    branches:
      - trunk

# Comment on wordpress-develop PRs to inform WordPress developers 
# about the new preview feature built with WordPress Playground.
# 
# @see build.yml
# @see https://github.com/WordPress/wordpress-develop/pull/5526
# @see https://github.com/WordPress/wordpress-playground/pull/700
# @see https://github.com/WordPress/wordpress-develop/pull/5481
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const previewLink = `https://playground.wordpress.net/wordpress.html?pr=${context.issue.number}`;
            const issueComment = `You can preview this Pull Request in [WordPress Playground](https://developer.wordpress.org/playground/), 
            an experimental environment that securely runs WordPress inside your web browser:
              
            [Click here to preview](${previewLink})
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            })
    
