name: Comment on PR

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.workflow_run.pull_requests[0].number;
            const identifier = '<!-- preview-link-comment -->';
            const issueComments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: prNumber,
            });
            
            const existingComment = issueComments.data.find(comment => comment.body.includes(identifier));
            if (existingComment) {
              console.log('Preview link comment already exists, skipping.');
              return;
            }
            
            const previewLink = `https://playground.wordpress.net/wordpress.html?pr=${prNumber}`;
            const issueComment = `${identifier}\nPreview link: [${previewLink}](${previewLink})`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: issueComment,
            });
