name: Comment on PR

on:
  pull_request:
    branches:
      - trunk

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
          GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
        with:
          github-token: ${{ env.BOT_TOKEN }}
          script: |
            const previewLink = `https://playground.wordpress.net/wordpress.html?pr=${context.issue.number}`;
            const issueComment = `Preview link: [${previewLink}](${previewLink})`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            })
    
