##
# DEPRECATED: A reusable workflow that builds WordPress and stores the result as an artifact for PHPUnit testing.
##
name: Build WordPress Artifact

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run tests on'
        required: false
        type: 'string'
        default: 'ubuntu-latest'

env:
  PUPPETEER_SKIP_DOWNLOAD: ${{ true }}

jobs:
  # Sets up WordPress for testing or development use.
  #
  # Performs the following steps:
  # - Cancels all previous workflow runs for pull requests that have not completed.
  # - Checks out the repository.
  # - Logs debug information about the GitHub Action runner.
  # - Installs NodeJS.
  # _ Installs npm dependencies.
  # - Builds WordPress to run from the `build` directory.
  # - Uploads WordPress as an artifact.
  setup-wordpress:
    name: Setup WordPress
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Log debug information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_EVENT_NAME"
          npm --version
          node --version
          curl --version
          git --version

      - name: Set up Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build WordPress
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: built-wp-${{ github.sha }}
          path: |
            !*.git/**
            !**/node_modules/**
            !packagehash.txt
          if-no-files-found: error
