name: WordPress Core Test Suite

on: [push]

env:
  LOCAL_DIR: build

jobs:
  set-up:
    name: Set up the environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use the desired version of Node using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install Dependencies
        run: npm install
      - name: Build WordPress
        run: npm run build
  test-php-8:
    name: Test PHP 8
    needs: set-up
    env:
      LOCAL_PHP: 8.0-fpm
    steps:
      - run: npm run env:start
      - run: npm run env:install

  test-php-7-4:
    name: Test PHP 7.4
    needs: set-up
    env:
      LOCAL_PHP: 7.4-fpm
    steps:
      - run: npm run env:start
      - run: npm run env:install
