name: WordPress Core Test Suite

on: [push]

env:
  LOCAL_DIR: build

jobs:
  test-php-7-4:
    name: Test PHP 7.4
    runs-on: ubuntu-latest
    env:
      LOCAL_PHP: 7.4-fpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout the WordPress Importer plugin
        run: svn checkout -r 2387243 https://plugins.svn.wordpress.org/wordpress-importer/trunk/ tests/phpunit/data/plugins/wordpress-importer

      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

#      - name: Use the desired version of Node using nvm
#        run: nvm install

      - name: Log debug information
        run: |
          npm --version
          which npm
          node --version
          curl --version
          git --version
          svn --version
          php --version
          php -i
          locale -a

      - name: Install Dependencies
        run: npm ci

      - name: Start Docker environment
        run: |
          npm run env:start

      - name: Build WordPress
        run: npm run build

      - name: Setup Docker environment
        run: |
          docker-compose run --rm mysql mysql --version
          docker-compose run --rm php php --version
          docker-compose run --rm php php -m
          npm run env:install

      - name: Run PHPUnit
        run: |
          npm run test:php -- --verbose -c phpunit.xml.dist &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group ajax &&
          npm run test:php -- --verbose -c tests/phpunit/multisite.xml &&
          npm run test:php -- --verbose -c tests/phpunit/multisite.xml --group ms-files &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group external-http &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group restapi-jsclient &&

  test-logging:
    name: Some test information
    runs-on: ubuntu-latest
    steps:
      - run: docker-compose -v
