name: WordPress Core Test Suite

on: [push]

env:
  LOCAL_DIR: build

jobs:
  test-php-8:
    name: Test PHP 8
    runs-on: ubuntu-latest
    env:
      LOCAL_PHP: 8.0-fpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use the desired version of Node using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install Dependencies
        run: npm ci --no-save
      - name: Start Docker environment
        run: |
          npm run env:start
      - name: Build WordPress
        run: npm run build
      - name: Setup Docker environment
        run: |
          docker-compose run --rm mysql mysql --version
          docker-compose run --rm php php --version
          docker-compose run --rm php php -m
          npm run env:install
      - name: Run PHPUnit
        run: |
          npm run test:php -- --verbose -c phpunit.xml.dist &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group ajax &&
          npm run test:php -- --verbose -c tests/phpunit/multisite.xml &&
          npm run test:php -- --verbose -c tests/phpunit/multisite.xml --group ms-files &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group external-http &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group restapi-jsclient &&

  test-php-7-4:
    name: Test PHP 7.4
    runs-on: ubuntu-latest
    env:
      LOCAL_PHP: 7.4-fpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use the desired version of Node using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install Dependencies
        run: npm ci --no-save
      - name: Start Docker environment
        run: |
          npm run env:start
      - name: Build WordPress
        run: npm run build
      - name: Setup Docker environment
        run: |
          docker-compose run --rm mysql mysql --version
          docker-compose run --rm php php --version
          docker-compose run --rm php php -m
          npm run env:install
      - name: Run PHPUnit
        run: |
          npm run test:php -- --verbose -c phpunit.xml.dist &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group ajax &&
          npm run test:php -- --verbose -c tests/phpunit/multisite.xml &&
          npm run test:php -- --verbose -c tests/phpunit/multisite.xml --group ms-files &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group external-http &&
          npm run test:php -- --verbose -c phpunit.xml.dist --group restapi-jsclient &&

  test-logging:
    name: Some test information
    runs-on: ubuntu-latest
    steps:
      - run: |
        docker-compose -v
