name: WordPress Core Test Suite

on: [push]

env:
  LOCAL_DIR: build

jobs:
  test-php-8:
    name: Test PHP 8
    runs-on: ubuntu-latest
    env:
      LOCAL_PHP: 8.0-fpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use the desired version of Node using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install Dependencies
        run: npm install
      - name: Build WordPress
        run: npm run build
      - name: Start Docker environment
        run: npm run env:start
      - name: Install WordPress within the Docker environment
        run: npm run env:install
      - name: Run PHPUnit
        run: npm run test:php

  test-php-7-4:
    name: Test PHP 7.4
    runs-on: ubuntu-latest
    env:
      LOCAL_PHP: 7.4-fpm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use the desired version of Node using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install Dependencies
        run: npm install
      - name: Build WordPress
        run: npm run build
      - name: Start Docker environment
        run: npm run env:start
      - name: Install WordPress within the Docker environment
        run: npm run env:install
      - name: Run PHPUnit
        run: npm run test:php
