name: Test NPM

on:
  push:
    branches:
      - master
      - '3.[7-9]'
      - '[4-9].[0-9]'
  pull_request:
    branches:
      - master
      - '3.[7-9]'
      - '[4-9].[0-9]'

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${{ true }}

jobs:
  # Prepares the workflow.
  #
  # Performs the following steps:
  # - Cancels all previous workflow runs for pull requests that have not completed.
  prepare-workflow:
    name: Prepare the workflow
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}

    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  # Verifies that installing NPM dependencies and building WordPress works on Windows.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Logs debug information about the runner container.
  # - Installs NodeJS 14.
  # - Sets up caching for NPM.
  # _ Installs NPM dependencies using install-changed to hash the `package.json` file.
  # - Builds WordPress to run from the `build` directory.
  test-npm:
    name: Tests NPM on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache NodeJS modules (Ubuntu & MacOS)
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Get NPM cache directory (Windows only)
        if: ${{ matrix.os == 'windows-latest' }}
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache NodeJS modules (Windows only)
        uses: actions/cache@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npx install-changed --install-command="npm ci"

      - name: Build WordPress
        run: npm run build

      - name: Clean after building
        run: npm run grunt clean

      - name: Build WordPress in /src
        run: npm run build:dev

      - name: Clean after building in /src
        run: npm run grunt clean --dev

