##
# A callable workflow that tests the WordPress Core build process.
##
name: Test the WordPress Build Process

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run tests on'
        required: false
        type: 'string'
        default: 'ubuntu-latest'

jobs:
  # Verifies that installing npm dependencies and building WordPress works as expected.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Logs debug information about the GitHub Action runner.
  # - Installs npm dependencies.
  # - Builds WordPress to run from the `build` directory.
  # - Cleans up after building WordPress to the `build` directory.
  # - Ensures version-controlled files are not modified or deleted.
  # - Builds WordPress to run from the `src` directory.
  # - Cleans up after building WordPress to the `src` directory.
  # - Ensures version-controlled files are not modified or deleted.
  build-process-tests:
    name: ${{ inputs.os == 'macos-latest' && 'MacOS' || inputs.os == 'windows-latest' && 'Windows' || 'Linux' }} / Core Build Process
    runs-on: ${{ inputs.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Set up Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Install npm Dependencies
        run: npm ci

      - name: Build WordPress in /src
        run: npm run build:dev

      - name: Clean after building in /src
        run: npm run grunt clean -- --dev

      - name: Ensure version-controlled files are not modified or deleted during building and cleaning
        run: git diff --exit-code

      - name: Build WordPress
        run: npm run build

      - name: Clean after building
        run: npm run grunt clean

      - name: Ensure version-controlled files are not modified or deleted during building and cleaning
        run: git diff --exit-code
