name: Test NPM on Windows

on:
  push:
    branches:
      - master
      - '*.*'
  pull_request:

jobs:
  # Verifies that installing NPM dependencies and building WordPress works on Windows.
  #
  # Performs the following steps:
  # - Cancels all previous workflow runs that have not completed.
  # - Checks out the repository.
  # - Reads the desired version of NodeJS from the .nvmrc file.
  # - Logs debug information about the runner container.
  # - Installs the desired NodeJS version.
  # - Sets up caching for NPM.
  # _ Installs NPM dependencies.
  # - Builds WordPress to run from the `build` directory.
  test-npm:
    name: Tests NPM on Windows
    runs-on: windows-latest
    steps:
      - name: Cancel previous runs of this workflow
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check the desired version of NodeJS
        run: echo "::set-output NODE_VERSION=$(cat .nvmrc)"

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get NPM cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache NodeJS modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        run: npm ci

      - name: Build WordPress
        run: npm run build
